name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18, 20]
        os: [macos-14, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --build-from-source

    - name: Run Tests
      run: npm test

    - name: Run Example Script
      run: node example.js

    - name: Publish Binaries (Non-Windows)
      if: ${{ matrix.os != 'windows-latest' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: ./node_modules/.bin/node-pre-gyp package unpublish publish info

    - name: Publish Windows Binaries
      if: >
        contains(github.event.commits[0].message, 'publish binary') &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/master' &&
        matrix.os == 'windows-latest'
      run: cmd /c 'node_modules\.bin\node-pre-gyp package unpublish publish info'
